#!/usr/bin/env node
/**
 * deploy-all.js
 *
 * Runs on every push via GitHub Actions.
 * For each config in generator/configs/:
 *   1. Generates the site (node generator/generate.js <name>)
 *   2. Injects PostHog key
 *   3. Writes a temporary wrangler.toml for the site
 *   4. Deploys to Cloudflare Workers via wrangler
 *
 * Required env vars:
 *   CLOUDFLARE_API_TOKEN   — Cloudflare API token with Workers write permission
 *   CLOUDFLARE_ACCOUNT_ID  — Cloudflare account ID
 *   LITEAPI_KEY            — LiteAPI production key (set as Worker secret)
 *
 * The LITEAPI_KEY secret must be pre-set on each Worker via:
 *   npx wrangler secret put LITEAPI_KEY --name <worker-name>
 * or via the Cloudflare dashboard. This script does NOT set secrets
 * (wrangler secret put requires interactive input or piping).
 */

const fs    = require('fs');
const path  = require('path');
const { execSync } = require('child_process');

const ACCOUNT_ID  = process.env.CLOUDFLARE_ACCOUNT_ID;
const CONFIGS_DIR = path.join(__dirname, 'generator', 'configs');
const SITES_DIR   = path.join(__dirname, 'sites');
const WORKER_FILE = path.join(__dirname, 'worker.js');

if (!ACCOUNT_ID) {
  console.error('❌  CLOUDFLARE_ACCOUNT_ID is not set');
  process.exit(1);
}

if (!process.env.CLOUDFLARE_API_TOKEN) {
  console.error('❌  CLOUDFLARE_API_TOKEN is not set');
  process.exit(1);
}

// ── Write a temporary wrangler.toml for a given site ────────
function writeTempWranglerToml(name) {
  const content = `# Auto-generated by deploy-all.js for ${name}
name = "${name}"
main = "worker.js"
compatibility_date = "2024-09-23"
account_id = "${ACCOUNT_ID}"

[assets]
directory = "sites/${name}"
`;
  const tomlPath = path.join(__dirname, 'wrangler.toml');
  fs.writeFileSync(tomlPath, content, 'utf8');
  return tomlPath;
}

// ── Main ──────────────────────────────────────────────────────
async function main() {
  const allConfigs = fs.readdirSync(CONFIGS_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => path.basename(f, '.json'));

  // Skip configs with skip_deploy: true
  const configs = allConfigs.filter(name => {
    const cfgPath = path.join(CONFIGS_DIR, `${name}.json`);
    const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));
    if (cfg.skip_deploy) {
      console.log(`  ⏭  Skipping ${name} (skip_deploy: true)`);
      return false;
    }
    return true;
  });

  console.log(`\n🚀  Deploying ${configs.length} site(s) to Cloudflare Workers: ${configs.join(', ')}\n`);

  const results = [];

  for (const name of configs) {
    console.log(`\n── ${name} ──────────────────────────`);

    // 1. Generate
    console.log(`  Generating...`);
    execSync(`node generator/generate.js ${name}`, { stdio: 'inherit' });

    // 2. PostHog key is now injected at generate time via {{POSTHOG_KEY}} token in config

    // 3. Write wrangler.toml for this site
    writeTempWranglerToml(name);
    console.log(`  ✓ wrangler.toml written for ${name}`);

    // 4. Deploy to Cloudflare Workers
    console.log(`  Deploying to Cloudflare Workers...`);
    try {
      execSync(`npx wrangler deploy`, {
        stdio: 'inherit',
        env: { ...process.env }
      });
      const workerUrl = `https://${name}.${ACCOUNT_ID.slice(0, 8)}.workers.dev`;
      console.log(`  ✅  ${name} deployed`);
      results.push({ name, status: 'ok' });
    } catch (err) {
      console.error(`  ❌  ${name} deploy failed: ${err.message}`);
      results.push({ name, status: 'failed', error: err.message });
    }
  }

  // Restore the default wrangler.toml for luxstay (the primary site)
  writeTempWranglerToml('luxstay');
  console.log(`\n✓ Restored wrangler.toml to luxstay default`);

  // Summary
  console.log(`\n── Deploy Summary ──────────────────────────`);
  const ok = results.filter(r => r.status === 'ok');
  const failed = results.filter(r => r.status === 'failed');
  console.log(`  ✅  ${ok.length} succeeded: ${ok.map(r => r.name).join(', ') || 'none'}`);
  if (failed.length) {
    console.log(`  ❌  ${failed.length} failed: ${failed.map(r => r.name).join(', ')}`);
    process.exit(1);
  }

  console.log(`\n✅  All sites deployed to Cloudflare Workers.\n`);
}

main().catch(err => {
  console.error('❌ ', err.message);
  process.exit(1);
});
