#!/usr/bin/env node
/**
 * autoresearch/seo-pages.js
 *
 * Generates city-level SEO landing pages for a site config.
 * Each city gets its own /london.html, /dubai.html etc with:
 *   - Unique title + meta description targeting long-tail keywords
 *   - Schema.org ItemList of hotels
 *   - Rich editorial content (generated by Claude)
 *   - Internal links back to the main search
 *   - Sitemap entry
 *
 * Usage:
 *   node autoresearch/seo-pages.js --site maldives-escape
 *   node autoresearch/seo-pages.js --site luxstay
 *
 * Outputs to: sites/<site-name>/<city-slug>.html  + sitemap.xml
 *
 * Required env vars (optional — falls back to templated content):
 *   ANTHROPIC_API_KEY — for AI-generated editorial paragraphs
 */

const fs   = require('fs');
const path = require('path');

const CONFIGS_DIR  = path.join(__dirname, '..', 'generator', 'configs');
const SITES_DIR    = path.join(__dirname, '..', 'sites');
const ANTHROPIC_KEY = process.env.ANTHROPIC_API_KEY;
const ANTHROPIC_API = 'https://api.anthropic.com/v1/messages';

const args    = process.argv.slice(2);
const getArg  = (flag, def) => { const i = args.indexOf(flag); return i >= 0 && args[i+1] ? args[i+1] : def; };
const SITE    = getArg('--site', null);

if (!SITE) {
  console.error('Usage: node autoresearch/seo-pages.js --site <name>');
  process.exit(1);
}

// ── Claude helper ─────────────────────────────────────────────
async function callClaude(prompt) {
  if (!ANTHROPIC_KEY) return null;
  const res = await fetch(ANTHROPIC_API, {
    method: 'POST',
    headers: {
      'x-api-key': ANTHROPIC_KEY,
      'anthropic-version': '2023-06-01',
      'content-type': 'application/json'
    },
    body: JSON.stringify({
      model: 'claude-haiku-4-5-20251001',
      max_tokens: 1024,
      messages: [{ role: 'user', content: prompt }]
    })
  });
  if (!res.ok) return null;
  const data = await res.json();
  return data.content[0].text;
}

// ── Slug helper ───────────────────────────────────────────────
function toSlug(str) {
  return str.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

// ── Build hotel schema items ──────────────────────────────────
function buildHotelSchema(hotels, siteUrl) {
  const items = hotels.map((h, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    item: {
      '@type': 'Hotel',
      name: h.name,
      description: h.desc,
      address: { '@type': 'PostalAddress', addressLocality: h.area }
    }
  }));
  return JSON.stringify({ '@context': 'https://schema.org', '@type': 'ItemList', itemListElement: items });
}

// ── Generate editorial for a city ────────────────────────────
async function getCityEditorial(brand, city, hotels, cfg) {
  const hotelNames = hotels.map(h => h.name).join(', ');

  if (ANTHROPIC_KEY) {
    const text = await callClaude(
      `Write 3 short paragraphs (4-5 sentences each) of SEO-friendly editorial content for a luxury hotel booking page targeting the keyword "${city} luxury hotels member rates".
Brand name: ${brand}
Hotels covered: ${hotelNames}
Key angle: members save 10-30% vs Booking.com through a closed user group platform.
Write naturally, mention the specific hotels, include the savings angle, mention that rates are live and updated in real time.
Plain HTML paragraphs only (<p> tags), no headings, no markdown.`
    );
    if (text) return text;
  }

  // Fallback template
  return `<p>${city} is one of the world's most sought-after destinations for luxury travellers, home to some of the finest hotels on the planet — including ${hotels[0]?.name} and ${hotels[1]?.name || hotels[0]?.name}. ${brand} gives verified members access to these properties at net rates 10–30% below what Booking.com, Expedia, and Hotels.com publish publicly.</p>
<p>These below-retail rates exist because hotels release unsold inventory through Closed User Group (CUG) channels as check-in approaches. ${brand} is a CUG platform — free to join — that gives you access to those rates the moment you become a member. Same hotel, same room, same dates: just a materially better price.</p>
<p>Rates on ${brand} are live and updated in real time, so the prices you see reflect genuine current availability. The best ${city} member rates typically appear from Wednesday onwards as hotels release unsold rooms ahead of the weekend. Last-minute travellers consistently see the deepest discounts.</p>`;
}

// ── Build a city page ─────────────────────────────────────────
async function buildCityPage(cfg, city, hotels, siteUrl) {
  const slug       = toSlug(city);
  const brand      = cfg.BRAND_NAME;
  const primary    = cfg.COLOR_PRIMARY;
  const accent     = cfg.COLOR_ACCENT;
  const accentLt   = cfg.COLOR_ACCENT_LT;
  const editorial  = await getCityEditorial(brand, city, hotels, cfg);
  const schemaJSON = buildHotelSchema(hotels, siteUrl);

  const metaTitle = `${city} Luxury Hotels — Member Rates | ${brand}`;
  const metaDesc  = `Save 10–30% on ${city} luxury hotels with ${brand} member pricing. ${hotels.slice(0,3).map(h=>h.name).join(', ')} and more. Live rates, no minimum stay.`;

  const hotelCards = hotels.map(h => `
    <div style="background:#fff;border:1px solid #e5e3de;border-radius:8px;padding:16px 20px;margin-bottom:12px">
      <div style="font-size:17px;font-weight:700;color:${primary};margin-bottom:4px">${h.emoji} ${h.name}</div>
      <div style="font-size:13px;color:#6b6b6b;margin-bottom:6px">📍 ${h.area} · ${h.dist}</div>
      <div style="font-size:13px;color:#6b6b6b;line-height:1.5;margin-bottom:8px">${h.desc}</div>
      <div style="display:flex;gap:6px;flex-wrap:wrap">${h.tags.map(t=>`<span style="font-size:11px;padding:3px 8px;border-radius:3px;background:#f7f7f5;border:1px solid #e5e3de;color:#6b6b6b">${t}</span>`).join('')}</div>
    </div>`).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>${metaTitle}</title>
  <meta name="description" content="${metaDesc}" />
  <link rel="canonical" href="${siteUrl}/${slug}.html" />
  <script type="application/ld+json">${schemaJSON}</script>
  <style>
    *,*::before,*::after{box-sizing:border-box;margin:0;padding:0}
    body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;background:#f7f7f5;color:#1a1a1a;line-height:1.5}
    nav{background:${primary};padding:0 24px;height:56px;display:flex;align-items:center;justify-content:space-between}
    .logo{font-size:20px;font-weight:700;color:${accent};letter-spacing:.04em;text-decoration:none}
    .main{max-width:860px;margin:0 auto;padding:32px 16px 64px}
    h1{font-size:clamp(22px,4vw,34px);font-weight:700;color:${primary};line-height:1.2;margin-bottom:12px}
    .hero-sub{font-size:16px;color:#6b6b6b;margin-bottom:32px;line-height:1.6}
    h2{font-size:20px;font-weight:700;color:${primary};margin:32px 0 16px}
    .editorial{background:#fff;border:1px solid #e5e3de;border-radius:6px;padding:24px;margin-bottom:32px}
    .editorial p{font-size:14px;color:#6b6b6b;line-height:1.7;margin-bottom:12px}
    .editorial p:last-child{margin-bottom:0}
    .cta-box{background:${primary};border-radius:8px;padding:32px;text-align:center;margin:32px 0}
    .cta-box h3{color:#fff;font-size:20px;font-weight:700;margin-bottom:8px}
    .cta-box p{color:rgba(255,255,255,.7);font-size:14px;margin-bottom:20px}
    .btn-cta{background:${accent};color:${primary};font-size:15px;font-weight:700;padding:13px 28px;border-radius:6px;text-decoration:none;display:inline-block}
    footer{background:${primary};color:rgba(255,255,255,.5);text-align:center;padding:24px;font-size:13px}
    .breadcrumb{font-size:13px;color:#6b6b6b;margin-bottom:20px}
    .breadcrumb a{color:${primary};text-decoration:none}
  </style>
</head>
<body>

<nav>
  <a href="/" class="logo">${brand}</a>
  <a href="/" style="color:rgba(255,255,255,.7);font-size:13px;text-decoration:none">← All destinations</a>
</nav>

<main class="main">

  <p class="breadcrumb"><a href="/">Home</a> › ${city}</p>

  <h1>${city} Luxury Hotel Member Rates</h1>
  <p class="hero-sub">Save 10–30% on ${city}'s finest hotels with ${brand} member pricing. Live rates, no minimum stay. ${hotels.length} hotels available.</p>

  <div class="editorial">
    ${editorial}
  </div>

  <h2>${city} hotels on ${brand}</h2>
  ${hotelCards}

  <div class="cta-box">
    <h3>Unlock member rates — it's free</h3>
    <p>Join ${brand} in 10 seconds and see prices 10–30% below Booking.com on all ${city} hotels.</p>
    <a href="/?city=${encodeURIComponent(city)}" class="btn-cta">Search ${city} hotels →</a>
  </div>

</main>

<footer>
  <p>© ${new Date().getFullYear()} ${brand} · ${cfg.FOOTER_TAGLINE}</p>
  <p style="margin-top:6px;font-size:11px">Member prices only shown to verified members · Rates sourced live via hotel API</p>
</footer>

</body>
</html>`;
}

// ── Build sitemap ─────────────────────────────────────────────
function buildSitemap(siteUrl, cityPages) {
  const today = new Date().toISOString().slice(0,10);
  const urls = [
    `  <url><loc>${siteUrl}/</loc><lastmod>${today}</lastmod><priority>1.0</priority></url>`,
    ...cityPages.map(p => `  <url><loc>${siteUrl}/${p}</loc><lastmod>${today}</lastmod><priority>0.8</priority></url>`)
  ].join('\n');
  return `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>`;
}

// ── Main ──────────────────────────────────────────────────────
async function main() {
  const cfgPath = path.join(CONFIGS_DIR, `${SITE}.json`);
  if (!fs.existsSync(cfgPath)) { console.error(`Config not found: ${cfgPath}`); process.exit(1); }
  const cfg = JSON.parse(fs.readFileSync(cfgPath, 'utf8'));

  const outDir  = path.join(SITES_DIR, SITE);
  fs.mkdirSync(outDir, { recursive: true });

  const siteUrl    = cfg.SCHEMA_URL || `https://${SITE}.netlify.app`;
  const cityPages  = [];

  console.log(`\n📄  Generating SEO pages for ${SITE} (${cfg.cities?.length || 0} cities)\n`);

  for (const cityObj of (cfg.cities || [])) {
    const city   = cityObj.value;
    const hotels = cfg.hotels?.[city] || [];
    if (!hotels.length) { console.log(`  ⏭  ${city} — no hotels, skipping`); continue; }

    console.log(`  Building: ${city} (${hotels.length} hotels)...`);
    const html = await buildCityPage(cfg, city, hotels, siteUrl);
    const slug  = toSlug(city);
    const filename = `${slug}.html`;
    fs.writeFileSync(path.join(outDir, filename), html, 'utf8');
    cityPages.push(filename);
    console.log(`  ✓ ${filename}`);
  }

  // Sitemap
  const sitemap = buildSitemap(siteUrl, cityPages);
  fs.writeFileSync(path.join(outDir, 'sitemap.xml'), sitemap, 'utf8');
  console.log(`  ✓ sitemap.xml (${cityPages.length + 1} URLs)`);

  // robots.txt
  const robots = `User-agent: *\nAllow: /\nSitemap: ${siteUrl}/sitemap.xml\n`;
  fs.writeFileSync(path.join(outDir, 'robots.txt'), robots, 'utf8');
  console.log(`  ✓ robots.txt`);

  console.log(`\n✅  Done. ${cityPages.length} SEO pages + sitemap + robots.txt\n`);
  console.log(`   Commit and push to deploy. Pages will be live at:`);
  cityPages.forEach(p => console.log(`     ${siteUrl}/${p}`));
  console.log('');
}

main().catch(e => { console.error('❌', e.message); process.exit(1); });
